# This file configures https://pre-commit.com/
# to use specific hooks and options.

default_language_version:
  node: system
exclude: |
  (?x)^(
    (.*/)?package-lock\.json|
    (.*/)?poetry\.lock
  )$
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe  # needed for parsing CFN
      - id: end-of-file-fixer
      - id: file-contents-sorter
        files: |
          (?x)^(
            \.dockerignore|
            \.gitignore
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        exclude: |
          (?x)^(
            (.*)?(cdk|package|tsconfig|tslint)\.json
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
        files: |
          (?x)^(
            (.*)?(cdk|package|tsconfig|tslint)\.json
          )$
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
  - repo: local
    hooks:
      - id: yamlfmt
        name: Format YAML files with overrides
        description: Format YAML files with overrides
        entry: python -m pre_commit_hooks.yamlfmt
        language: python
        types: [yaml]
        additional_dependencies:
          - ./
          - click
          - ruamel.yaml
        exclude: .pre-commit-hooks.yaml
        args: [--mapping, '2', --offset, '2', --sequence, '4', --preserve-quotes]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-tables
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.40.0
    hooks:
      - id: markdownlint
