# This file configures https://pre-commit.com/
# to use specific hooks and options.

fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe       # needed for parsing CFN
      - id: end-of-file-fixer
        exclude: .*\.json-result
      - id: file-contents-sorter
        files: |
          (?x)^(
            \.gitignore|
            \.vscode/dictionaries/.*\.txt
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '4']
        files: |
          (?x)^(
            \.vscode/.*\.json
          )$
      - id: pretty-format-json
        args: [--autofix, --indent, '2']
        files: |
          (?x)^(
            package.json
          )$
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: yamlfmt
        name: Format YAML files with overrides
        description: Format YAML files with overrides
        entry: python -m pre_commit_hooks.yamlfmt
        language: python
        types: [yaml]
        additional_dependencies:
          - ./
          - ruamel.yaml
        exclude: .pre-commit-hooks.yaml
        args: [--mapping, '2', --offset, '2', --sequence, '4', --preserve-quotes]
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-frontmatter
          - mdformat-gfm
          - mdformat-toc
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
      - id: markdownlint
