name: default

on:
  pull_request:  # any pull request
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
env:
  NODE_VERSION: '20'
  PYTEST_ADDOPTS: --color=yes

jobs:
  lint-python:
    name: Lint Python
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, '3.10', 3.11, 3.12]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm ci
      - uses: ITProKyle/action-setup-python@v1.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: make lint
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: make setup-npm
      - run: make spellcheck
  test-python:
    name: Python Tests
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, '3.10', 3.11, 3.12]
    steps:
      - uses: actions/checkout@v5
      - uses: ITProKyle/action-setup-python@v1.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - run: make test
